main: blue.dev.warps.Main
name: Warps
version: 1.9.5
author: Blue1
commands:
  warp:
    usage: /<command> [warpName]
    description: Warps a player!
  warps:
    usage: /<command>
    description: Send a list of warps!
  setwarp:
    usage: /<command> [warpName]
    description: Creates a warp!
  delwarp:
    usage: /<command> [warpName]
    description: Deletes a warp!